import java.io.File;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Map;
import java.util.HashMap;

public class GenerateFiles {
    public static void main(String[] args) throws Exception {
        String basePath = "d:/future tech/backend/src/main/java/com/futuretech";
        String entityPath = basePath + "/entity";
        String enumsPath = entityPath + "/enums";
        String repoPath = basePath + "/repository";

        new File(enumsPath).mkdirs();
        new File(repoPath).mkdirs();

        Map<String, String> files = new HashMap<>();

        // Enums
        files.put(enumsPath + "/UserType.java", "package com.futuretech.entity.enums;\npublic enum UserType { ADMIN, STUDENT }\n");
        files.put(enumsPath + "/InstitutionType.java", "package com.futuretech.entity.enums;\npublic enum InstitutionType { SCHOOL, COLLEGE }\n");
        files.put(enumsPath + "/EducationType.java", "package com.futuretech.entity.enums;\npublic enum EducationType { SCHOOL, ENGINEERING, ARTS_SCIENCE, POLYTECHNIC, OTHER }\n");
        files.put(enumsPath + "/ProfileStatus.java", "package com.futuretech.entity.enums;\npublic enum ProfileStatus { INCOMPLETE, COMPLETED }\n");
        files.put(enumsPath + "/StudentStatus.java", "package com.futuretech.entity.enums;\npublic enum StudentStatus { PENDING_APPROVAL, APPROVED, REJECTED, ACTIVE, INACTIVE }\n");
        files.put(enumsPath + "/FeeStatus.java", "package com.futuretech.entity.enums;\npublic enum FeeStatus { PENDING, PARTIALLY_PAID, PAID, OVERDUE, CANCELLED }\n");
        files.put(enumsPath + "/PaymentMethod.java", "package com.futuretech.entity.enums;\npublic enum PaymentMethod { CASH, UPI, BANK_TRANSFER, CARD }\n");
        files.put(enumsPath + "/AttendanceStatus.java", "package com.futuretech.entity.enums;\npublic enum AttendanceStatus { PRESENT, ABSENT }\n");
        files.put(enumsPath + "/TargetType.java", "package com.futuretech.entity.enums;\npublic enum TargetType { ALL_STUDENTS, STUDENT, INSTITUTION, DEPARTMENT, ACADEMIC_BATCH }\n");
        files.put(enumsPath + "/TaskStatus.java", "package com.futuretech.entity.enums;\npublic enum TaskStatus { PENDING, IN_PROGRESS, COMPLETED }\n");
        files.put(enumsPath + "/EmailType.java", "package com.futuretech.entity.enums;\npublic enum EmailType { STUDENT_REGISTRATION, STUDENT_APPROVAL }\n");
        files.put(enumsPath + "/EmailStatus.java", "package com.futuretech.entity.enums;\npublic enum EmailStatus { PENDING, SENT, FAILED }\n");

        // Entities
        files.put(entityPath + "/User.java", "package com.futuretech.entity;\nimport com.futuretech.entity.enums.UserType;\nimport jakarta.persistence.*;\nimport lombok.*;\nimport java.time.LocalDateTime;\n\n@Entity\n@Table(name = \"users\")\n@Data @NoArgsConstructor @AllArgsConstructor @Builder\npublic class User {\n    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)\n    private Long id;\n    \n    @Column(nullable = false) private String name;\n    @Column(nullable = false, unique = true) private String email;\n    @Column(name = \"password_hash\", nullable = false) private String passwordHash;\n    \n    @Enumerated(EnumType.STRING)\n    @Column(name = \"user_type\", nullable = false) private UserType userType;\n    \n    private String phone;\n    @Column(name = \"is_active\") private Boolean isActive = true;\n    \n    @Column(name = \"created_at\", updatable = false) private LocalDateTime createdAt;\n    @Column(name = \"updated_at\") private LocalDateTime updatedAt;\n    \n    @PrePersist protected void onCreate() { createdAt = LocalDateTime.now(); updatedAt = LocalDateTime.now(); }\n    @PreUpdate protected void onUpdate() { updatedAt = LocalDateTime.now(); }\n}\n");

        files.put(entityPath + "/Institution.java", "package com.futuretech.entity;\nimport com.futuretech.entity.enums.InstitutionType;\nimport jakarta.persistence.*;\nimport lombok.*;\nimport java.time.LocalDateTime;\n\n@Entity\n@Table(name = \"institutions\")\n@Data @NoArgsConstructor @AllArgsConstructor @Builder\npublic class Institution {\n    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)\n    private Long id;\n    \n    @Column(name = \"institution_name\", nullable = false) private String institutionName;\n    @Enumerated(EnumType.STRING)\n    @Column(name = \"institution_type\", nullable = false) private InstitutionType institutionType;\n    \n    private String location;\n    @Column(name = \"is_active\") private Boolean isActive = true;\n    \n    @Column(name = \"created_at\", updatable = false) private LocalDateTime createdAt;\n    @Column(name = \"updated_at\") private LocalDateTime updatedAt;\n    \n    @PrePersist protected void onCreate() { createdAt = LocalDateTime.now(); updatedAt = LocalDateTime.now(); }\n    @PreUpdate protected void onUpdate() { updatedAt = LocalDateTime.now(); }\n}\n");

        files.put(entityPath + "/Department.java", "package com.futuretech.entity;\nimport jakarta.persistence.*;\nimport lombok.*;\nimport java.time.LocalDateTime;\n\n@Entity\n@Table(name = \"departments\")\n@Data @NoArgsConstructor @AllArgsConstructor @Builder\npublic class Department {\n    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)\n    private Long id;\n    \n    @ManyToOne(fetch = FetchType.LAZY)\n    @JoinColumn(name = \"institution_id\")\n    private Institution institution;\n    \n    @Column(name = \"department_name\", nullable = false) private String departmentName;\n    @Column(name = \"department_code\") private String departmentCode;\n    @Column(name = \"is_active\") private Boolean isActive = true;\n    \n    @Column(name = \"created_at\", updatable = false) private LocalDateTime createdAt;\n    @Column(name = \"updated_at\") private LocalDateTime updatedAt;\n    \n    @PrePersist protected void onCreate() { createdAt = LocalDateTime.now(); updatedAt = LocalDateTime.now(); }\n    @PreUpdate protected void onUpdate() { updatedAt = LocalDateTime.now(); }\n}\n");

        files.put(entityPath + "/Student.java", "package com.futuretech.entity;\nimport com.futuretech.entity.enums.*;\nimport jakarta.persistence.*;\nimport lombok.*;\nimport java.time.LocalDate;\nimport java.time.LocalDateTime;\n\n@Entity\n@Table(name = \"students\")\n@Data @NoArgsConstructor @AllArgsConstructor @Builder\npublic class Student {\n    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)\n    private Long id;\n    \n    @OneToOne(fetch = FetchType.LAZY)\n    @JoinColumn(name = \"user_id\", nullable = false)\n    private User user;\n    \n    @Column(name = \"student_code\", unique = true) private String studentCode;\n    @Column(name = \"first_name\") private String firstName;\n    @Column(name = \"last_name\") private String lastName;\n    @Column(name = \"date_of_birth\") private LocalDate dateOfBirth;\n    private String gender;\n    private String phone;\n    private String address;\n    private String city;\n    \n    @Enumerated(EnumType.STRING)\n    @Column(name = \"education_type\") private EducationType educationType;\n    \n    @ManyToOne(fetch = FetchType.LAZY)\n    @JoinColumn(name = \"institution_id\")\n    private Institution institution;\n    \n    @ManyToOne(fetch = FetchType.LAZY)\n    @JoinColumn(name = \"department_id\")\n    private Department department;\n    \n    @Column(name = \"class_standard\") private String classStandard;\n    private String section;\n    @Column(name = \"academic_year\") private String academicYear;\n    \n    @Column(name = \"joining_year\") private Integer joiningYear;\n    @Column(name = \"passing_year\") private Integer passingYear;\n    @Column(name = \"academic_batch\") private String academicBatch;\n    \n    @Column(name = \"parent_name\") private String parentName;\n    @Column(name = \"parent_phone\") private String parentPhone;\n    @Column(name = \"profile_photo_url\") private String profilePhotoUrl;\n    @Column(name = \"joining_date\") private LocalDate joiningDate;\n    \n    @Enumerated(EnumType.STRING)\n    @Column(name = \"profile_status\") private ProfileStatus profileStatus = ProfileStatus.INCOMPLETE;\n    \n    @Enumerated(EnumType.STRING)\n    private StudentStatus status = StudentStatus.PENDING_APPROVAL;\n    \n    @Column(name = \"created_at\", updatable = false) private LocalDateTime createdAt;\n    @Column(name = \"updated_at\") private LocalDateTime updatedAt;\n    \n    @PrePersist protected void onCreate() { createdAt = LocalDateTime.now(); updatedAt = LocalDateTime.now(); }\n    @PreUpdate protected void onUpdate() { updatedAt = LocalDateTime.now(); }\n}\n");

        files.put(entityPath + "/FeeRecord.java", "package com.futuretech.entity;\nimport com.futuretech.entity.enums.FeeStatus;\nimport jakarta.persistence.*;\nimport lombok.*;\nimport java.math.BigDecimal;\nimport java.time.LocalDate;\nimport java.time.LocalDateTime;\n\n@Entity\n@Table(name = \"fee_records\")\n@Data @NoArgsConstructor @AllArgsConstructor @Builder\npublic class FeeRecord {\n    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)\n    private Long id;\n    \n    @ManyToOne(fetch = FetchType.LAZY)\n    @JoinColumn(name = \"student_id\", nullable = false)\n    private Student student;\n    \n    @Column(name = \"fee_name\", nullable = false) private String feeName;\n    @Column(name = \"total_amount\", nullable = false) private BigDecimal totalAmount;\n    @Column(name = \"discount_amount\") private BigDecimal discountAmount;\n    @Column(name = \"final_amount\", nullable = false) private BigDecimal finalAmount;\n    \n    @Column(name = \"due_date\") private LocalDate dueDate;\n    \n    @Enumerated(EnumType.STRING)\n    private FeeStatus status = FeeStatus.PENDING;\n    \n    @Column(name = \"created_at\", updatable = false) private LocalDateTime createdAt;\n    @Column(name = \"updated_at\") private LocalDateTime updatedAt;\n    \n    @PrePersist protected void onCreate() { createdAt = LocalDateTime.now(); updatedAt = LocalDateTime.now(); }\n    @PreUpdate protected void onUpdate() { updatedAt = LocalDateTime.now(); }\n}\n");

        files.put(entityPath + "/Payment.java", "package com.futuretech.entity;\nimport com.futuretech.entity.enums.PaymentMethod;\nimport jakarta.persistence.*;\nimport lombok.*;\nimport java.math.BigDecimal;\nimport java.time.LocalDate;\nimport java.time.LocalDateTime;\n\n@Entity\n@Table(name = \"payments\")\n@Data @NoArgsConstructor @AllArgsConstructor @Builder\npublic class Payment {\n    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)\n    private Long id;\n    \n    @ManyToOne(fetch = FetchType.LAZY)\n    @JoinColumn(name = \"fee_record_id\", nullable = false)\n    private FeeRecord feeRecord;\n    \n    @ManyToOne(fetch = FetchType.LAZY)\n    @JoinColumn(name = \"student_id\", nullable = false)\n    private Student student;\n    \n    @Column(nullable = false) private BigDecimal amount;\n    @Column(name = \"payment_date\", nullable = false) private LocalDate paymentDate;\n    \n    @Enumerated(EnumType.STRING)\n    @Column(name = \"payment_method\", nullable = false) private PaymentMethod paymentMethod;\n    \n    @Column(name = \"transaction_id\") private String transactionId;\n    @Column(name = \"receipt_number\", unique = true) private String receiptNumber;\n    private String remarks;\n    \n    @Column(name = \"created_at\", updatable = false) private LocalDateTime createdAt;\n    \n    @PrePersist protected void onCreate() { createdAt = LocalDateTime.now(); }\n}\n");

        files.put(entityPath + "/Attendance.java", "package com.futuretech.entity;\nimport com.futuretech.entity.enums.AttendanceStatus;\nimport jakarta.persistence.*;\nimport lombok.*;\nimport java.time.LocalDate;\nimport java.time.LocalDateTime;\n\n@Entity\n@Table(name = \"attendance\")\n@Data @NoArgsConstructor @AllArgsConstructor @Builder\npublic class Attendance {\n    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)\n    private Long id;\n    \n    @ManyToOne(fetch = FetchType.LAZY)\n    @JoinColumn(name = \"student_id\", nullable = false)\n    private Student student;\n    \n    @Column(name = \"attendance_date\", nullable = false) private LocalDate attendanceDate;\n    \n    @Enumerated(EnumType.STRING)\n    @Column(nullable = false) private AttendanceStatus status;\n    \n    private String remarks;\n    \n    @Column(name = \"created_at\", updatable = false) private LocalDateTime createdAt;\n    \n    @PrePersist protected void onCreate() { createdAt = LocalDateTime.now(); }\n}\n");

        files.put(entityPath + "/Task.java", "package com.futuretech.entity;\nimport jakarta.persistence.*;\nimport lombok.*;\nimport java.time.LocalDate;\nimport java.time.LocalDateTime;\n\n@Entity\n@Table(name = \"tasks\")\n@Data @NoArgsConstructor @AllArgsConstructor @Builder\npublic class Task {\n    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)\n    private Long id;\n    \n    @Column(nullable = false) private String title;\n    private String description;\n    \n    @ManyToOne(fetch = FetchType.LAZY)\n    @JoinColumn(name = \"created_by\", nullable = false)\n    private User createdBy;\n    \n    @Column(name = \"created_date\", nullable = false) private LocalDate createdDate;\n    @Column(name = \"due_date\") private LocalDate dueDate;\n    \n    @Column(name = \"created_at\", updatable = false) private LocalDateTime createdAt;\n    @Column(name = \"updated_at\") private LocalDateTime updatedAt;\n    \n    @PrePersist protected void onCreate() { createdAt = LocalDateTime.now(); updatedAt = LocalDateTime.now(); }\n    @PreUpdate protected void onUpdate() { updatedAt = LocalDateTime.now(); }\n}\n");

        files.put(entityPath + "/TaskTarget.java", "package com.futuretech.entity;\nimport com.futuretech.entity.enums.TargetType;\nimport jakarta.persistence.*;\nimport lombok.*;\nimport java.time.LocalDateTime;\n\n@Entity\n@Table(name = \"task_targets\")\n@Data @NoArgsConstructor @AllArgsConstructor @Builder\npublic class TaskTarget {\n    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)\n    private Long id;\n    \n    @ManyToOne(fetch = FetchType.LAZY)\n    @JoinColumn(name = \"task_id\", nullable = false)\n    private Task task;\n    \n    @Enumerated(EnumType.STRING)\n    @Column(name = \"target_type\", nullable = false) private TargetType targetType;\n    \n    @ManyToOne(fetch = FetchType.LAZY)\n    @JoinColumn(name = \"student_id\")\n    private Student student;\n    \n    @ManyToOne(fetch = FetchType.LAZY)\n    @JoinColumn(name = \"institution_id\")\n    private Institution institution;\n    \n    @ManyToOne(fetch = FetchType.LAZY)\n    @JoinColumn(name = \"department_id\")\n    private Department department;\n    \n    @Column(name = \"academic_batch\") private String academicBatch;\n    \n    @Column(name = \"created_at\", updatable = false) private LocalDateTime createdAt;\n    \n    @PrePersist protected void onCreate() { createdAt = LocalDateTime.now(); }\n}\n");

        files.put(entityPath + "/StudentTask.java", "package com.futuretech.entity;\nimport com.futuretech.entity.enums.TaskStatus;\nimport jakarta.persistence.*;\nimport lombok.*;\nimport java.time.LocalDateTime;\n\n@Entity\n@Table(name = \"student_tasks\")\n@Data @NoArgsConstructor @AllArgsConstructor @Builder\npublic class StudentTask {\n    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)\n    private Long id;\n    \n    @ManyToOne(fetch = FetchType.LAZY)\n    @JoinColumn(name = \"task_id\", nullable = false)\n    private Task task;\n    \n    @ManyToOne(fetch = FetchType.LAZY)\n    @JoinColumn(name = \"student_id\", nullable = false)\n    private Student student;\n    \n    @Enumerated(EnumType.STRING)\n    private TaskStatus status = TaskStatus.PENDING;\n    \n    @Column(name = \"completed_at\") private LocalDateTime completedAt;\n    private String remarks;\n    \n    @Column(name = \"created_at\", updatable = false) private LocalDateTime createdAt;\n    @Column(name = \"updated_at\") private LocalDateTime updatedAt;\n    \n    @PrePersist protected void onCreate() { createdAt = LocalDateTime.now(); updatedAt = LocalDateTime.now(); }\n    @PreUpdate protected void onUpdate() { updatedAt = LocalDateTime.now(); }\n}\n");

        files.put(entityPath + "/Notification.java", "package com.futuretech.entity;\nimport jakarta.persistence.*;\nimport lombok.*;\nimport java.time.LocalDateTime;\n\n@Entity\n@Table(name = \"notifications\")\n@Data @NoArgsConstructor @AllArgsConstructor @Builder\npublic class Notification {\n    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)\n    private Long id;\n    \n    @ManyToOne(fetch = FetchType.LAZY)\n    @JoinColumn(name = \"student_id\", nullable = false)\n    private Student student;\n    \n    @Column(nullable = false) private String title;\n    @Column(nullable = false) private String message;\n    @Column(name = \"notification_type\") private String notificationType;\n    \n    @Column(name = \"is_read\") private Boolean isRead = false;\n    \n    @Column(name = \"created_at\", updatable = false) private LocalDateTime createdAt;\n    \n    @PrePersist protected void onCreate() { createdAt = LocalDateTime.now(); }\n}\n");

        files.put(entityPath + "/EmailLog.java", "package com.futuretech.entity;\nimport com.futuretech.entity.enums.EmailStatus;\nimport com.futuretech.entity.enums.EmailType;\nimport jakarta.persistence.*;\nimport lombok.*;\nimport java.time.LocalDateTime;\n\n@Entity\n@Table(name = \"email_logs\")\n@Data @NoArgsConstructor @AllArgsConstructor @Builder\npublic class EmailLog {\n    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)\n    private Long id;\n    \n    @ManyToOne(fetch = FetchType.LAZY)\n    @JoinColumn(name = \"student_id\")\n    private Student student;\n    \n    @Column(nullable = false) private String email;\n    private String subject;\n    \n    @Enumerated(EnumType.STRING)\n    @Column(name = \"email_type\", nullable = false) private EmailType emailType;\n    \n    @Enumerated(EnumType.STRING)\n    private EmailStatus status = EmailStatus.PENDING;\n    \n    @Column(name = \"sent_at\") private LocalDateTime sentAt;\n    @Column(name = \"error_message\") private String errorMessage;\n    \n    @Column(name = \"created_at\", updatable = false) private LocalDateTime createdAt;\n    \n    @PrePersist protected void onCreate() { createdAt = LocalDateTime.now(); }\n}\n");

        // Repositories
        files.put(repoPath + "/UserRepository.java", "package com.futuretech.repository;\nimport com.futuretech.entity.User;\nimport org.springframework.data.jpa.repository.JpaRepository;\nimport org.springframework.stereotype.Repository;\nimport java.util.Optional;\n\n@Repository\npublic interface UserRepository extends JpaRepository<User, Long> {\n    Optional<User> findByEmail(String email);\n}\n");
        files.put(repoPath + "/InstitutionRepository.java", "package com.futuretech.repository;\nimport com.futuretech.entity.Institution;\nimport org.springframework.data.jpa.repository.JpaRepository;\nimport org.springframework.stereotype.Repository;\n\n@Repository\npublic interface InstitutionRepository extends JpaRepository<Institution, Long> {}\n");
        files.put(repoPath + "/DepartmentRepository.java", "package com.futuretech.repository;\nimport com.futuretech.entity.Department;\nimport org.springframework.data.jpa.repository.JpaRepository;\nimport org.springframework.stereotype.Repository;\n\n@Repository\npublic interface DepartmentRepository extends JpaRepository<Department, Long> {}\n");
        files.put(repoPath + "/StudentRepository.java", "package com.futuretech.repository;\nimport com.futuretech.entity.Student;\nimport org.springframework.data.jpa.repository.JpaRepository;\nimport org.springframework.stereotype.Repository;\nimport java.util.Optional;\n\n@Repository\npublic interface StudentRepository extends JpaRepository<Student, Long> {\n    Optional<Student> findByStudentCode(String studentCode);\n    Optional<Student> findByUserId(Long userId);\n}\n");
        files.put(repoPath + "/FeeRecordRepository.java", "package com.futuretech.repository;\nimport com.futuretech.entity.FeeRecord;\nimport org.springframework.data.jpa.repository.JpaRepository;\nimport org.springframework.stereotype.Repository;\nimport java.util.List;\n\n@Repository\npublic interface FeeRecordRepository extends JpaRepository<FeeRecord, Long> {\n    List<FeeRecord> findByStudentId(Long studentId);\n}\n");
        files.put(repoPath + "/PaymentRepository.java", "package com.futuretech.repository;\nimport com.futuretech.entity.Payment;\nimport org.springframework.data.jpa.repository.JpaRepository;\nimport org.springframework.stereotype.Repository;\nimport java.util.List;\n\n@Repository\npublic interface PaymentRepository extends JpaRepository<Payment, Long> {\n    List<Payment> findByStudentId(Long studentId);\n}\n");
        files.put(repoPath + "/AttendanceRepository.java", "package com.futuretech.repository;\nimport com.futuretech.entity.Attendance;\nimport org.springframework.data.jpa.repository.JpaRepository;\nimport org.springframework.stereotype.Repository;\nimport java.util.List;\nimport java.time.LocalDate;\n\n@Repository\npublic interface AttendanceRepository extends JpaRepository<Attendance, Long> {\n    List<Attendance> findByStudentId(Long studentId);\n    boolean existsByStudentIdAndAttendanceDate(Long studentId, LocalDate attendanceDate);\n}\n");
        files.put(repoPath + "/TaskRepository.java", "package com.futuretech.repository;\nimport com.futuretech.entity.Task;\nimport org.springframework.data.jpa.repository.JpaRepository;\nimport org.springframework.stereotype.Repository;\n\n@Repository\npublic interface TaskRepository extends JpaRepository<Task, Long> {}\n");
        files.put(repoPath + "/TaskTargetRepository.java", "package com.futuretech.repository;\nimport com.futuretech.entity.TaskTarget;\nimport org.springframework.data.jpa.repository.JpaRepository;\nimport org.springframework.stereotype.Repository;\nimport java.util.List;\n\n@Repository\npublic interface TaskTargetRepository extends JpaRepository<TaskTarget, Long> {\n    List<TaskTarget> findByTaskId(Long taskId);\n}\n");
        files.put(repoPath + "/StudentTaskRepository.java", "package com.futuretech.repository;\nimport com.futuretech.entity.StudentTask;\nimport org.springframework.data.jpa.repository.JpaRepository;\nimport org.springframework.stereotype.Repository;\nimport java.util.List;\n\n@Repository\npublic interface StudentTaskRepository extends JpaRepository<StudentTask, Long> {\n    List<StudentTask> findByStudentId(Long studentId);\n}\n");
        files.put(repoPath + "/NotificationRepository.java", "package com.futuretech.repository;\nimport com.futuretech.entity.Notification;\nimport org.springframework.data.jpa.repository.JpaRepository;\nimport org.springframework.stereotype.Repository;\nimport java.util.List;\n\n@Repository\npublic interface NotificationRepository extends JpaRepository<Notification, Long> {\n    List<Notification> findByStudentId(Long studentId);\n}\n");
        files.put(repoPath + "/EmailLogRepository.java", "package com.futuretech.repository;\nimport com.futuretech.entity.EmailLog;\nimport org.springframework.data.jpa.repository.JpaRepository;\nimport org.springframework.stereotype.Repository;\n\n@Repository\npublic interface EmailLogRepository extends JpaRepository<EmailLog, Long> {}\n");

        for (Map.Entry<String, String> entry : files.entrySet()) {
            Files.write(Paths.get(entry.getKey()), entry.getValue().getBytes());
        }
        System.out.println("Generated files successfully.");
    }
}
